import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "../globals.css";

import AppProvider from '@/components/appContext'
import NavBar from "@/components/product/NavBar";
const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function Layout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="dark">
      <body className={inter.className}>
        <AppProvider>
          <NavBar/>
        {children}
        </AppProvider>
      </body>
    </html>
  );
}
